Don't assume the package version is the same as the as the release ve…
HuddleEng/octopose pull request #36
Opened 2018-06-20 15:29 UTC by george-ayris

…rsion

Fixes #33 

A little bit messy because we have to combine information from three sources: the list of packageIds from the manifest file, the step names and versions from the Release and the packageIds and step names from the DeploymentSnapshot associated with the Release. The  `get_package_versions` is what has this logic - not the most efficient, but these lists are going to be pretty small.

Have also improved the `print` output so that it's more explicit about what Release version and Package versions are actually being deployed.

2018-06-20 22:35 UTC, domgreen requested changes
LGTM - just a nit or 2

2018-06-20 22:35 UTC, domgreen commented on CHANGELOG.md
> +* Allow deploying of packages that have a different version to the release version ([#33](https://github.com/HuddleEng/octopose/issues/330))
`33`

2018-06-20 22:35 UTC, domgreen commented on octopose/local_deploy.py
> +
nit - unneeded whitespace

2018-06-20 22:35 UTC, domgreen commented on octopose/local_deploy.py
> +            print("{0} - {1}".format(project_name, release_version))
personally would add a blank line above this and remove the one below ... but meh whatever you like ;)

2018-06-20 22:35 UTC, domgreen commented on octopose/local_deploy.py
> +            print("{0} - {1}".format(project_name, release_version))
Also might be an idea to move to structured logging at some point, this looks nice http://www.structlog.org/en/stable/ but maybe not for the size of this project.

2018-06-20 22:35 UTC, domgreen commented on octopose/octo.py
> +def get_specific_package_ids(release, environment_id=None):
add method comment

2018-06-20 22:35 UTC, domgreen commented on octopose/octo.py
> +    return [p["PackageId"] for p in packages]
your getting fancy 🎩

2018-06-20 22:38 UTC, domgreen requested changes

2018-06-20 22:38 UTC, domgreen commented on octopose/local_deploy.py
> +    for p in step_names_and_version:
what is `p`?

2018-06-20 22:38 UTC, domgreen commented on octopose/local_deploy.py
> +        for pp in package_ids_and_step_names:
i could live with `p` but `pp`

2018-06-22 13:35 UTC, george-ayris commented
Cheers, the nitpick is useful

2018-06-22 13:37 UTC, merged